### ISSUE TITLE
Not able to make it run

### ISSUE THREAD

**Issue by mkg123** [jbarker7/sqlcc#10]
I tried the video on this site and that usage is not working. It would be helpful, if the exact usage can be provided. 
Also, if the same trace file name is provided, instead of throwing error.. is it possible to overwrite the same file

**Comment by kiranvenu** [comment]
I too followed the steps provided in the site, but nothing is working.

**Comment by stefanteixeira** [comment]
+1

I imported the project on Visual Studio and it does not build, there's some issue with the copy.bat file.

Detailed instructions would be great. I'm wanting to use the project, but I'm definitely not familiar with C# and Visual Studio, so it's kinda hard to setup everything without any explanation.

Could any contributor give some help with this? @JakubLinhart @jbarker7

**Comment by jbarker7** [comment]
@stefanteixeira have you tried a "Rebuild"?

**Comment by jbarker7** [comment]
@mk123 The exact usage should be documented on the main page- what problems are you experiencing?

**Comment by jbarker7** [comment]
Changed the build order on the project- should work now.  Please open a new issue if you have any issues.

**Comment by stefanteixeira** [comment]
@jbarker7 The build order was the problem.

**Comment by stefanteixeira** [comment]
@jbarker7 I tried to contact you by email months ago, but got no response. I'm using the project at the company I work and I want to contribute. The project is great but there are still some documentation and project issues and I want to talk with you about that. Can you shoot me an email at stefanfk@gmail.com? :)
