### ISSUE TITLE
Need exact syntax to use, please

### ISSUE THREAD

**Issue by samratdeb** [jbarker7/sqlcc#12]
Hi, Can anyone please post the exact syntax to use the exe?

I don't understand some of the things in the parameter like:

a) what will be the application name?

b) in the below command line - 
sqlcc --app.mode=start --action=execute --target="mstest.exe" --targetArgs="/testcontainer:SQLCC.Sample.Tests.dll" --traceFileName="TraceF"

          1) what is target and targetArgs in the command line of the batch file?

Is my batch file going to run with the below syntax?

![image](https://cloud.githubusercontent.com/assets/9079938/10027954/9939ba16-611e-11e5-9747-3e19f322ef91.png)

Please suggest and help.

Thanks,
-Sam

**Comment by jbarker7** [comment]
Target is the full path to mstest.exe or if you're using nunit, it is nunit.exe.  TargetArgs is the arguments that are fed into mstest or nunit.

**Comment by samratdeb** [comment]
Thanks Josh, so, if I use mstest or nunit I don't have to provide the text exe file path that I provided in the middle line because if I use mstest then I will provide the test project dll only.. so no need to create another app to call the SPs.. Thanks in advance.

**Comment by jbarker7** [comment]
Basically, in the below statement, you will need to provide the exact path
to mstest.exe (your test runner) and the targetArgs provide where your
tests are (the assembly that runs your SQL code).  No need to create
another app that calls them, only provide your unit test assembly.

sqlcc --action=execute --target="mstest.exe"
--targetArgs="/testcontainer:SQLCC.Sample.Tests.dll"
--traceFileName="TraceFile"

**Comment by subbulive** [comment]
Hi Josh,

Wanted to check if i can use this as stand alone with out nunit or mstest .  using this with sqlcmd or profiler.exe alone in target and targetArgs
