### ISSUE TITLE
Constructor on type 'SQLCC.Impl.MsSqlProvider.MsSqlProvider' not found.

### ISSUE THREAD

**Issue by ghostsquad** [jbarker7/sqlcc#3]
Constructor on type 'SQLCC.Impl.MsSqlProvider.MsSqlProvider' not found.

AssemblyLoader.cs: Line 68

here's the line that the exception occurs on:
return (T)Activator.CreateInstance(type, args);

it's because args = object[0] and there is no constructor for MsSqlProvider that accepts that as input.

debugging GetNamedArgumentArray shows something interesting happen on line 84:

```C#
if (providedSignature != orderedParams) continue;
```

Here's the local variables being compared:
		orderedParams	"dbp.applicationName,dbp.connString,dbp.traceDir"	string
		providedSignature	"dbp.applicationName,dbp.connString,dbp.traceDir,dbp.traceName"	string

there are no other constructors, so the foreach ends, so then the last line of the method is:

```C#
return new object[0];
```

This error occurs when the config file is edited (per instructions from issue: KeyNotFoundException) (config addition below)

```XML
<add key="dbp.traceName" value="TraceFile" />
```

I've removed the above line from the config file, and added --app.traceName to the arguments when running the EXE and all seems well.  Looks like we need an update to support dbp.traceName in the config file.

**Comment by jbarker7** [comment]
Closed due to no response
