### ISSUE TITLE
Run #myTraceFile has not been completed successfully.

### ISSUE THREAD

**Issue by ghostsquad** [jbarker7/sqlcc#4]
Run #myTraceFile has not been completed successfully.

This is all that I can get to show up in default.html after starting/stopping.

Can you please add the source code for the JS files found in:

\sqlcc-master\SQLCC.Impl.HtmlCodeHighlighter\sqlcc_output.zip

several of these JS files are "minified", and I don't see those anywhere else in this repository.

**Comment by sarunya** [comment]
i still have the same issue

**Comment by samratdeb** [comment]
somehow its not working even for me...
I am making my own :)

**Comment by jbarker7** [comment]
Please let me know if this issue is still open.
